<?xml version="1.0"?>
<!DOCTYPE script PUBLIC	"-//Apache Software Foundation//Tapestry Script Specification 3.0//EN"
	"http://jakarta.apache.org/tapestry/dtd/Script_3_0.dtd">
<script>    
    <input-symbol key="inputId" required="yes"/>
    <input-symbol key="updateId" required="yes"/>   

	<initialization>    
        new Autocompleter.Local('${inputId}','${updateId}',new Array("one", "two", "three", "four", "five"),{tokens: ','});        
    </initialization>
</script>